Resources:  
  myVPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      Tags:
        - Key: "Name"
          Value: "myVPC"
  mySUBNET:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref myVPC #references myVPC id
      CidrBlock: 10.0.0.0/24
      MapPublicIpOnLaunch: 'true'
      Tags:
        - Key: "Name"
          Value: "mySUBNET"